sudo: required

addons:
  chrome: stable
  sonarcloud:
    organization: $SONAR_ORG
    token:
      secure: $SONAR_TOKEN

language: node_js
node_js:
  - "stable"

before_script:
  - npm install -g @angular/cli

script:
  - npm run test
  - npm run build
  - sonar-scanner

branches:
  only:
    - master

deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN

notifications:
  email:
    on_failure: change
    on_success: change
